---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multi-tenant-platform-api
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./platform-api
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: multi-tenant
  targetNamespace: flux-system
  timeout: 3m0s
  wait: true
  dependsOn:
    - name: integrations
