---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: multi-tenant
  namespace: flux-system
spec:
  interval: 5m0s
  url: ssh://git@github.com/acll19/multi-tenant.git
  ref:
    branch: main
  secretRef:
    name: multi-tenant-auth
